// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1.2 (64-bit)
// Version: 2022.1.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="dft_dft,hls_ip_2022_1_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.958120,HLS_SYN_LAT=524625,HLS_SYN_TPT=none,HLS_SYN_MEM=20,HLS_SYN_DSP=0,HLS_SYN_FF=10246,HLS_SYN_LUT=9821,HLS_VERSION=2022_1_2}" *)

module dft (
        ap_clk,
        ap_rst_n,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 13;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg   [7:0] sample_real_address0;
reg    sample_real_ce0;
reg    sample_real_we0;
wire   [63:0] sample_real_q0;
reg   [7:0] sample_imag_address0;
reg    sample_imag_ce0;
reg    sample_imag_we0;
wire   [63:0] sample_imag_q0;
reg   [7:0] temp_real_address0;
reg    temp_real_ce0;
reg    temp_real_we0;
wire   [63:0] temp_real_q0;
reg   [7:0] temp_imag_address0;
reg    temp_imag_ce0;
reg    temp_imag_we0;
wire   [63:0] temp_imag_q0;
wire    grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_ap_start;
wire    grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_ap_done;
wire    grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_ap_idle;
wire    grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_ap_ready;
wire   [7:0] grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_sample_real_address0;
wire    grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_sample_real_ce0;
wire   [7:0] grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_sample_imag_address0;
wire    grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_sample_imag_ce0;
wire   [7:0] grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_temp_real_address0;
wire    grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_temp_real_ce0;
wire    grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_temp_real_we0;
wire   [63:0] grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_temp_real_d0;
wire   [7:0] grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_temp_imag_address0;
wire    grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_temp_imag_ce0;
wire    grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_temp_imag_we0;
wire   [63:0] grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_temp_imag_d0;
wire    grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_ap_start;
wire    grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_ap_done;
wire    grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_ap_idle;
wire    grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_ap_ready;
wire   [7:0] grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_temp_real_address0;
wire    grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_temp_real_ce0;
wire   [7:0] grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_sample_real_address0;
wire    grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_sample_real_ce0;
wire    grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_sample_real_we0;
wire   [63:0] grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_sample_real_d0;
wire   [7:0] grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_temp_imag_address0;
wire    grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_temp_imag_ce0;
wire   [7:0] grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_sample_imag_address0;
wire    grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_sample_imag_ce0;
wire    grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_sample_imag_we0;
wire   [63:0] grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_sample_imag_d0;
reg    grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_ap_start_reg = 1'b0;
#0 grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_ap_start_reg = 1'b0;
end

dft_temp_real_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
temp_real_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(temp_real_address0),
    .ce0(temp_real_ce0),
    .we0(temp_real_we0),
    .d0(grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_temp_real_d0),
    .q0(temp_real_q0)
);

dft_temp_real_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
temp_imag_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(temp_imag_address0),
    .ce0(temp_imag_ce0),
    .we0(temp_imag_we0),
    .d0(grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_temp_imag_d0),
    .q0(temp_imag_q0)
);

dft_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2 grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_ap_start),
    .ap_done(grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_ap_done),
    .ap_idle(grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_ap_idle),
    .ap_ready(grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_ap_ready),
    .sample_real_address0(grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_sample_real_address0),
    .sample_real_ce0(grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_sample_real_ce0),
    .sample_real_q0(sample_real_q0),
    .sample_imag_address0(grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_sample_imag_address0),
    .sample_imag_ce0(grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_sample_imag_ce0),
    .sample_imag_q0(sample_imag_q0),
    .temp_real_address0(grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_temp_real_address0),
    .temp_real_ce0(grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_temp_real_ce0),
    .temp_real_we0(grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_temp_real_we0),
    .temp_real_d0(grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_temp_real_d0),
    .temp_imag_address0(grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_temp_imag_address0),
    .temp_imag_ce0(grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_temp_imag_ce0),
    .temp_imag_we0(grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_temp_imag_we0),
    .temp_imag_d0(grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_temp_imag_d0)
);

dft_dft_Pipeline_VITIS_LOOP_39_3 grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_ap_start),
    .ap_done(grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_ap_done),
    .ap_idle(grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_ap_idle),
    .ap_ready(grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_ap_ready),
    .temp_real_address0(grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_temp_real_address0),
    .temp_real_ce0(grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_temp_real_ce0),
    .temp_real_q0(temp_real_q0),
    .sample_real_address0(grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_sample_real_address0),
    .sample_real_ce0(grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_sample_real_ce0),
    .sample_real_we0(grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_sample_real_we0),
    .sample_real_d0(grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_sample_real_d0),
    .temp_imag_address0(grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_temp_imag_address0),
    .temp_imag_ce0(grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_temp_imag_ce0),
    .temp_imag_q0(temp_imag_q0),
    .sample_imag_address0(grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_sample_imag_address0),
    .sample_imag_ce0(grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_sample_imag_ce0),
    .sample_imag_we0(grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_sample_imag_we0),
    .sample_imag_d0(grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_sample_imag_d0)
);

dft_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .sample_real_address0(sample_real_address0),
    .sample_real_ce0(sample_real_ce0),
    .sample_real_we0(sample_real_we0),
    .sample_real_d0(grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_sample_real_d0),
    .sample_real_q0(sample_real_q0),
    .sample_imag_address0(sample_imag_address0),
    .sample_imag_ce0(sample_imag_ce0),
    .sample_imag_we0(sample_imag_we0),
    .sample_imag_d0(grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_sample_imag_d0),
    .sample_imag_q0(sample_imag_q0),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_ap_start_reg <= 1'b1;
        end else if ((grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_ap_ready == 1'b1)) begin
            grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_ap_start_reg <= 1'b1;
        end else if ((grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_ap_ready == 1'b1)) begin
            grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        sample_imag_address0 = grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_sample_imag_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        sample_imag_address0 = grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_sample_imag_address0;
    end else begin
        sample_imag_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        sample_imag_ce0 = grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_sample_imag_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        sample_imag_ce0 = grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_sample_imag_ce0;
    end else begin
        sample_imag_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        sample_imag_we0 = grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_sample_imag_we0;
    end else begin
        sample_imag_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        sample_real_address0 = grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_sample_real_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        sample_real_address0 = grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_sample_real_address0;
    end else begin
        sample_real_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        sample_real_ce0 = grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_sample_real_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        sample_real_ce0 = grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_sample_real_ce0;
    end else begin
        sample_real_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        sample_real_we0 = grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_sample_real_we0;
    end else begin
        sample_real_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        temp_imag_address0 = grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_temp_imag_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        temp_imag_address0 = grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_temp_imag_address0;
    end else begin
        temp_imag_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        temp_imag_ce0 = grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_temp_imag_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        temp_imag_ce0 = grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_temp_imag_ce0;
    end else begin
        temp_imag_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        temp_imag_we0 = grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_temp_imag_we0;
    end else begin
        temp_imag_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        temp_real_address0 = grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_temp_real_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        temp_real_address0 = grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_temp_real_address0;
    end else begin
        temp_real_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        temp_real_ce0 = grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_temp_real_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        temp_real_ce0 = grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_temp_real_ce0;
    end else begin
        temp_real_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        temp_real_we0 = grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_temp_real_we0;
    end else begin
        temp_real_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_ap_start = grp_dft_Pipeline_VITIS_LOOP_21_1_VITIS_LOOP_27_2_fu_62_ap_start_reg;

assign grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_ap_start = grp_dft_Pipeline_VITIS_LOOP_39_3_fu_86_ap_start_reg;

endmodule //dft
